<?php 
/**
 * @var \AHT\Blog\Block\Blog\Index $block
 */ 
?>

<div class="search-container">
    <input type="text" id="blog-search" name="search" placeholder="Search" value="" style="max-width: 80%;"/>
    <button id="blog-btn-search">Search</button>
    <select name="items-per-page" id="blog-items-per-page" style="max-width: 10%;">
        <option value="1" selected>1</option>
        <option value="5">5</option>
        <option value="10">10</option>
    </select>
</div>
<div class="blog-container">
</div>
<div class="pagination-container">
</div>