<div class="footer-link-col">
    <p class="footer-link-header">Categories</p>
    <p class="footer-link">Outdoor Lounges</p>
    <p class="footer-link">Outdoor Dining</p>
    <p class="footer-link">Outdoor Unbrellas & Accessories</p>
    <p class="footer-link">Wood Fireplaces</p>
    <p class="footer-link">Gas Fireplaces</p>
    <p class="footer-link">Ethanol Fireplaces</p>
    <p class="footer-link">Electric Fireplaces</p>
    <p class="footer-link">Weber Charcoal BBQs</p>
    <p class="footer-link">Weber Premium Gas BBQs</p>
    <p class="footer-link">Weber Qs</p>
    <p class="footer-link">Weber Electric BBQs</p>
    <p class="footer-link">Clearance Store</p>
</div>
<div class="footer-link-col">
    <p class="footer-link-header">Why Burning Log?</p>
    <p class="footer-link">About us</p>
    <p class="footer-link">All products</p>
    <p class="footer-link">Catalogues</p>
    <p class="footer-link">Contact us</p>
</div>
<div class="footer-link-col">
    <p class="footer-link-header">Our Policies</p>
    <p class="footer-link">Terms and conditions</p>
    <p class="footer-link">Return policies</p>
    <p class="footer-link">Delivery and pick up policies</p>
    <p class="footer-link">Privacy policy</p> 
</div>