<div class="home-banner">
    <span class="banner-text">Get summer ready with<br/>our exclusive outdoor furniture</span>
    <button class="banner-button">SHOP OUTDOOR DAYBEDS ></button>
</div>
<div class="home-sub-banner">
    <div class="banner-big-container">
        <div class="banner-big">
            <span class="banner-text">OUTDOOR DINING</span>
            <button class="banner-button">SHOP NOW ></button>
        </div>
        <div class="banner-big">
            <span class="banner-text">OUTDOOR LOUNGES</span>
            <button class="banner-button">SHOP NOW ></button>
        </div>
    </div>
    <div class="banner-divider">
        <span>OUTDOOR FURNITURE CLEARANCE STORE ></span>
        <span>WE SHIP AUSTRALIA WIDE ></span>
        <span>30 DAY MONEY BACK GURANTEE ></span>
    </div>
    <div class="banner-small-container">
        <div class="banner-small">
            <div class="banner-image"></div>
            <div class="banner-description">
                <span class="banner-text-header">Vogue Collection</span>
                <span class="banner-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</span>
                <button class="banner-button">SHOP NOW ></button>
            </div>
        </div>
        <div class="banner-small">
            <div class="banner-image"></div>
            <div class="banner-description">
                <span class="banner-text-header">Maldives Collection</span>
                <span class="banner-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</span>
                <button class="banner-button">SHOP NOW ></button>
            </div>
        </div>
        <div class="banner-small">
            <div class="banner-image"></div>
            <div class="banner-description">
                <span class="banner-text-header">Marseilles Collection</span>
                <span class="banner-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</span>
                <button class="banner-button">SHOP NOW ></button>
            </div>
            
        </div>
    </div>
    <div class="banner-big-container">
        <div class="banner-big">
            <span class="banner-text">CATALOGUES</span>
            <button class="banner-button">EXPLORE NOW ></button>
        </div>
        <div class="banner-big">
            
        </div>
    </div>
</div>
<div class="home-best-seller">
    <h1 class="home-section-header">Best sellers</h1>
    <div class="home-item-list">
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 3pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price">$1,495.00</p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 5pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price">$2,495.00</p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 6pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price">$2,995.00</p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 3pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price"><s>$2,995.00</s> <span class="item-price-discount">$1,295.00</span></p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
    </div>
</div>
<div class="home-new-arrivals">
    <h1 class="home-section-header">New Arrivals</h1>
    <div class="home-item-list">
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 3pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price">$1,495.00</p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 5pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price">$2,495.00</p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 6pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price">$2,995.00</p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
        <div class ="home-item">
            <div class="home-item-image"></div>
            <div class="home-item-description">
                <p class="item-subtext">More colours available</p>
                <p class="item-text">Maldives Sunbrella 3pc Outdoor Modular Sofa Setting - Moonscape/Canvas Coal</p>
                <p class="item-price"><s>$2,995.00</s> <span class="item-price-discount">$1,295.00</span></p>
                <button class="item-button">ADD TO CART</button>
            </div>
        </div>
    </div>
</div>
<div class="home-instagram">
    <h1 class="home-section-header">Outdoor inspiration with our instagram</h1>
    <p class="home-section-sub-header">Find us at @burninglog, show us your future with #burninglog</p>
    <div class="home-instagram-images">
        <div class="home-instagram-image"></div>
        <div class="home-instagram-image"></div>
        <div class="home-instagram-image"></div>
        <div class="home-instagram-image"></div>
        <div class="home-instagram-image"></div>
    </div>
    <div class="home-instagram-button">
        <button>VIEW OUR INSTAGRAM</button>
    </div>
</div>
<div class="home-blog">
    <h1 class="home-section-header">Lifestyle Blog</h1>
    <div class="home-blog-row">
        <div class="home-blog-post">
            <div class="blog-image"></div>
            <div class="blog-summary">
                <p class="blog-header">Add a burst of colour to your backyard</p>
                <p class="blog-body">Introducing the Sunbrella ottoman collection, an exciting set of new outdoor accessory pieces that will liven up any outdoor lounge setting...</p>
                <a href="#" class="view-more">View more</a>
            </div>
        </div>
        <div class="home-blog-post">
            <div class="blog-image"></div>
            <div class="blog-summary">
                <p class="blog-header">The Maldives modular collection</p>
                <p class="blog-body">Outdoor modular lounges are enjoying extraordinary popularity at the moment as we look to bring the comforts of the lounge room into the great outdoors...</p>
                <a href="#" class="view-more">View more</a>
            </div>
        </div>
        <div class="home-blog-post">
            <div class="blog-image"></div>
            <div class="blog-summary">
                <p class="blog-header">Outdoor furniture trends - this years hottest wicker colour</p>
                <p class="blog-body">After launching the colour last year we are finding our "Moonscape" synthetic wicker colour extraordinary popular. It really has given weather wicker outdoor furniture...</p>
                <a href="#" class="view-more">View more</a>
            </div>
        </div>
    </div>
    <div class="home-blog-row">
        <div class="home-blog-post">
            <div class="blog-image"></div>
            <div class="blog-summary">
                <p class="blog-header">Is this the best outdoor table in Australia?</p>
                <p class="blog-body">When it comes to furniture materials suitable for extended life in the Australian outdoors it is hard to go past aluminium. It is very light and will not rust which makes...</p>
                <a href="#" class="view-more">View more</a>
            </div>
        </div>
        <div class="home-blog-post">
            <div class="blog-image"></div>
            <div class="blog-summary">
                <p class="blog-header">The undeniable elegance of cast aluminium</p>
                <p class="blog-body">Having used cast aluminium outdoor furniture for years in our dining range we are still unsure if its growing popularity is due more to its elegance look or the superb performance qualities...</p>
                <a href="#" class="view-more">View more</a>
            </div>
        </div>
        <div class="home-blog-post">
            <div class="blog-image"></div>
            <div class="blog-summary">
                <p class="blog-header">Christmas decorating for your outdoor setting</p>
                <p class="blog-body">When decorating for Christmas, many people remember to decorate the house, the yard and the Christmas tree but what about the dining room table?</p>
                <a href="#" class="view-more">View more</a>
            </div>
        </div>
    </div>
</div>
<div class="home-testimonials">
    <h1 class="home-section-header">Burning Log Testimonials</h1>
    <div class="home-testimonials-row">
        <div class="testimonial-card">
            <p class="testimonial-content">We just had our outdoor seating delivered. A massive thank you to Tony (Melbourne store) for your service. You went above and beyond, and you always... <a href="#" class="view-more">View more</a></p>
            <p class="testimonial-author">Rebecca</p>
            <p class="testimonial-date">November 17, 2016</p>
        </div>
        <div class="testimonial-card">
            <p class="testimonial-content">We just had our outdoor seating delivered. A massive thank you to Tony (Melbourne store) for your service. You went above and beyond, and you always... <a href="#" class="view-more">View more</a></p>
            <p class="testimonial-author">Rebecca</p>
            <p class="testimonial-date">November 17, 2016</p>
        </div>
    </div>
    <div class="home-testimonials-row">
        <div class="testimonial-card">
            <p class="testimonial-content">We have purchased an outdoor lounge from Outdoor Elegence and just want to say the experience was fantastic from the purchase to the delivery... <a href="#" class="view-more">View more</a></p>
            <p class="testimonial-author">Michelle</p>
            <p class="testimonial-date">November 29, 2016</p>
        </div>
        <div class="testimonial-card">
            <p class="testimonial-content">Excellent service from Tamara at Terry Hills. Lyon table and Maldives chairs arrived on Monday, counldn't be... <a href="#" class="view-more">View more</a></p>
            <p class="testimonial-author">Michelle</p>
            <p class="testimonial-date">November 29, 2016</p>
        </div>
    </div>
    <div class="testimonials-view-more">
        <button>VIEW MORE TESTIMONIALS</button>
    </div>
</div>
<div class="home-showroom">

</div>